In [ ]:
import pandas as pd
import numpy as np

#Constants
L1 = 'label_1'
L2 = 'label_2'
L3 = 'label_3'
L4 = 'label_4'
LABELS = [L1, L2, L3, L4]
AGE_LABEL = L2
FEATURES =  [f'feature_{i}' for i in range(1,257)]

In [ ]:
train_df = pd.read_csv("/content/sample_data/train.csv")
valid_df = pd.read_csv("/content/sample_data/valid.csv")
test_df = pd.read_csv("/content/sample_data/test.csv")

train_df.head()
valid_df.head()
test_df.head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  -1.141206  -0.279703   1.019681   2.605902   0.460391  -1.167380   
1  -1.796767  -0.056758   0.771219   4.414086  -1.229059   1.732098   
2  -1.388968  -0.418296   0.186543   2.803852  -1.499095   1.395180   
3   1.276844  -0.112323  -0.310796   2.251175   0.283670  -0.581020   
4  -1.560815  -0.168494   1.249770   1.869219  -1.646049   0.132156   

   feature_7  feature_8  feature_9  feature_10  ...  feature_251  feature_252  \
0  -1.149165  -1.205164   2.468966   -2.729526  ...    -0.868282    -0.429783   
1   0.063241  -0.126311   1.322355   -3.461282  ...     0.227806     0.209200   
2   0.739648   0.274060   1.228789   -3.081147  ...    -0.692679     0.449235   
3  -0.024439  -0.306097   2.424685   -1.714863  ...    -0.690499    -1.077949   
4  -0.664602   0.483327   1.728020   -2.258071  ...    -0.510597     1.213396   

   feature_253  feature_254  feature_255  feature_256  label_1  label_2  \
0     0.438561    -1.625122     0.599944    -0.615575      NaN      NaN   
1     2.200402    -1.701029     1.163999    -1.570136      NaN      NaN   
2     1.377531    -1.854203    -0.040538    -2.164104      NaN      NaN   
3     0.930102    -2.758352    -0.246738    -1.389013      NaN      NaN   
4     2.497490    -1.597984    -0.163483    -1.735939      NaN      NaN   

   label_3  label_4  
0      NaN      NaN  
1      NaN      NaN  
2      NaN      NaN  
3      NaN      NaN  
4      NaN      NaN  

[5 rows x 260 columns]

In [ ]:
train_df.info()
train_df[L1].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28520 entries, 0 to 28519
Columns: 260 entries, feature_1 to label_4
dtypes: float64(257), int64(3)
memory usage: 56.6 MB


12    485
35    484
26    483
60    482
24    482
25    481
59    481
10    481
54    481
45    480
41    480
9     480
2     479
42    479
47    479
6     479
56    479
34    478
52    478
3     478
14    478
33    478
43    477
1     477
13    477
20    477
23    477
30    476
51    476
32    476
53    476
22    476
38    476
49    476
55    475
28    474
8     474
40    474
48    474
21    474
4     474
39    473
17    473
7     473
15    472
58    472
5     471
27    471
31    470
19    469
11    469
46    469
29    469
36    468
16    468
50    467
37    467
44    467
57    466
18    465
Name: label_1, dtype: int64

In [ ]:
from pandas.core.arrays.period import validate_dtype_freq
# Scaling the data
from sklearn.preprocessing import RobustScaler # RobustScaler

x_train = {}
x_valid = {}
x_test = {}
y_train = {}
y_valid = {}

for target_label in LABELS:
  tr_df = train_df[train_df['label_2'].notna()] if target_label == 'label_2' else train_df # remove NA values in label 2
  vl_df = valid_df[valid_df['label_2'].notna()] if target_label == 'label_2' else valid_df
  t_df = test_df
  scaler = RobustScaler()
  x_train[target_label] = pd.DataFrame(scaler.fit_transform(tr_df.drop(LABELS, axis=1)), columns = FEATURES)
  x_test[target_label] = pd.DataFrame(scaler.fit_transform(t_df.drop(LABELS, axis=1)), columns = FEATURES)
  y_train[target_label] = tr_df[target_label]
  x_valid[target_label] = pd.DataFrame(scaler.transform(vl_df.drop(LABELS, axis=1)), columns = FEATURES)
  y_valid[target_label] = vl_df[target_label]

(750, 256)

**For Label 1**

Without Feature Engineering

In [ ]:
x_train[L1]

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0      -1.309586   0.235701   0.943739   1.110687   0.493583  -0.232368   
1      -1.144159  -0.295674   0.837377   2.514509  -0.718433   1.537233   
2      -1.292525   0.186803  -0.330437   2.726045  -0.915203   1.013608   
3       0.669594  -1.191524  -0.251777   0.560848   0.193810   0.728978   
4      -1.345805   0.084043   0.418116   2.155265  -0.227710   1.064978   
...          ...        ...        ...        ...        ...        ...   
28515   0.043336   1.192542  -0.149975   0.011312   2.636595  -0.068369   
28516   1.215430  -0.535137   0.051517  -0.021644   0.280856  -0.269055   
28517   0.997528  -0.016963   0.116092   0.297648   1.067387   0.208798   
28518  -0.605893  -0.008649   0.009349  -0.613440   0.888404  -0.589037   
28519   0.763188  -0.207126   0.459697  -0.435380   0.961052  -0.455518   

       feature_7  feature_8  feature_9  feature_10  ...  feature_247  \
0      -0.624554  -0.504571   0.132999    0.095217  ...     1.583006   
1       0.286751  -0.431414   1.105227   -0.783768  ...     1.036040   
2       1.247330  -1.564947   0.951931   -1.012765  ...     0.297848   
3       0.931314   0.170499   1.527067    0.288711  ...     0.829376   
4      -0.248008   0.090402   0.538791   -1.573073  ...     1.058010   
...          ...        ...        ...         ...  ...          ...   
28515  -0.978061   0.177880   1.175240    0.563477  ...     0.670030   
28516   0.761116  -1.611506  -0.137716    0.093801  ...     0.680854   
28517   0.236824  -0.038200   0.211088    0.628452  ...     0.334185   
28518   0.129601  -0.855883   0.201302   -0.727748  ...     0.465296   
28519   0.601866   0.921103  -1.020922    1.548995  ...     0.079121   

       feature_248  feature_249  feature_250  feature_251  feature_252  \
0         1.101137    -0.786061     0.622750    -0.503841    -0.862208   
1        -0.688550    -1.640606    -0.053767    -0.486404    -0.493145   
2         0.303437    -2.323521    -0.182392    -0.006368     0.086269   
3        -0.102070    -2.596694    -0.616500     0.544197     0.307588   
4        -0.117040    -1.419770     0.362046    -0.435119    -0.786176   
...            ...          ...          ...          ...          ...   
28515    -0.158732    -0.525769     1.257927     0.567362    -0.776576   
28516    -0.432984    -0.031154     0.887144    -0.127631     0.039676   
28517    -0.180739    -0.387017    -0.955283     0.850339    -1.401814   
28518     0.307306     0.663333     0.233262     0.540602    -0.434947   
28519    -0.087894    -1.330237    -0.403272     0.973497    -0.812996   

       feature_253  feature_254  feature_255  feature_256  
0        -1.063657    -0.033389    -0.726253     0.785181  
1        -1.293456    -0.320623     0.746471    -0.660619  
2         0.762691     0.577715    -0.946525    -0.585987  
3        -0.577020     0.401594    -1.154003     0.207497  
4         0.068403    -0.787532     1.939043     0.183946  
...            ...          ...          ...          ...  
28515    -0.718924     0.924023     0.570760     0.442692  
28516    -0.151647    -0.303670     0.903381    -0.282937  
28517     0.774752     1.397541    -0.214777    -0.206945  
28518     0.085522    -0.173189    -1.037877    -0.075089  
28519     1.066722     1.259609    -0.024581    -1.249044  

[28520 rows x 256 columns]

In [ ]:
# Training the model to predict label_1
from sklearn import svm

clf = svm.SVC(kernel='linear')

clf.fit(x_train[L1], y_train[L1])

SVC(kernel='linear')

In [ ]:
from sklearn import metrics

y_pred = clf.predict(x_valid[L1]) # Predicting the validation data set

In [ ]:
# accuracy of the validation data set
print(metrics.confusion_matrix(y_valid[L1], y_pred))
print(metrics.accuracy_score(y_valid[L1], y_pred))
print(metrics.precision_score(y_valid[L1], y_pred, average='weighted'))
print(metrics.recall_score(y_valid[L1], y_pred, average='weighted'))

[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.9906666666666667
0.9915571095571095
0.9906666666666667


In [ ]:
# predicting the label_1 of the test data set
y_pred_test = clf.predict(x_test[L1])

In [ ]:
y_pred_test

array([45, 45, 45, 45, 45, 45,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5, 60, 60, 60, 60, 60, 60, 60, 60, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 39, 19, 19, 19, 19, 19, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 25, 25, 25,
       25, 25, 25, 24, 25, 25, 25, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
       46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 51, 51, 51, 51, 51, 51, 51,
       51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 35, 35, 35, 35, 35, 35, 35,
       35, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 53, 53, 53, 53, 53,
       53, 22, 53, 53, 53,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 43, 43, 43, 43,
       43, 43, 43, 43, 43, 43, 43, 58, 58, 58, 58, 58, 58, 58, 58, 44, 44,
       44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55

With Feature Engineering

In [ ]:
# With  selectKBest method
from sklearn.feature_selection import SelectKBest, f_classif

selector =  SelectKBest(f_classif, k=150) #  with only using 150 features
x_new_train = selector.fit_transform(x_train[L1], y_train[L1])
x_new_valid = selector.transform(x_valid[L1])
x_new_test = selector.transform(x_test[L1])
print('shape training', x_new_train.shape)
print('shape validation', x_new_valid.shape)
print('shape test', x_new_test.shape)

shape training (28520, 150)
shape validation (750, 150)
shape test (750, 150)


In [ ]:
clf = svm.SVC(kernel='linear')

clf.fit(x_new_train, y_train[L1])

SVC(kernel='linear')

In [ ]:
y_pred = clf.predict(selector.transform(x_valid[L1]))
print(metrics.confusion_matrix(y_valid[L1], y_pred))
print(metrics.accuracy_score(y_valid[L1], y_pred))
print(metrics.precision_score(y_valid[L1], y_pred, average='weighted'))
print(metrics.recall_score(y_valid[L1], y_pred, average='weighted'))

[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  9]]
0.9826666666666667
0.9839200725200726
0.9826666666666667


In [ ]:
# adding PCA to the selectKBest results
from sklearn.decomposition import PCA

pca = PCA(n_components=0.95, svd_solver='full')
pca.fit(x_new_train)
x_train_trf = pd.DataFrame(pca.transform(x_new_train)) # transforming data to fit into pca
x_valid_trf = pd.DataFrame(pca.transform(x_new_valid))
x_test_trf = pd.DataFrame(pca.transform(x_new_test))
print('Shape after PCA x_train : ', x_train_trf.shape)
print('Shape after PCA x_valid : ', x_valid_trf.shape)
print('Shape after PCA x_test : ', x_valid_trf.shape)

Shape after PCA x_train :  (28520, 57)
Shape after PCA x_valid :  (750, 57)
Shape after PCA x_test :  (750, 57)


In [ ]:
clf = svm.SVC(kernel='linear')

clf.fit(x_train_trf, y_train[L1])

y_pred = clf.predict(x_valid_trf)
print(metrics.confusion_matrix(y_valid[L1], y_pred))
print(metrics.accuracy_score(y_valid[L1], y_pred))
print(metrics.precision_score(y_valid[L1], y_pred, average='weighted'))
print(metrics.recall_score(y_valid[L1], y_pred, average='weighted'))

[[11  0  0 ...  0  0  0]
 [ 0  8  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 18  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  9]]
0.9666666666666667
0.9697322862322861
0.9666666666666667


In [ ]:
# predicting the test data
y_pred_test_fe = clf.predict(x_test_trf)
y_pred_test_fe

array([45, 45, 45, 45, 45, 45,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5, 60, 60, 60, 60, 60, 60, 60, 60, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 39, 19, 19, 19, 19, 19, 11, 11, 11, 11, 11, 11, 34, 11, 11,
       11, 11, 11, 52, 36, 52, 52, 52, 52, 52, 52, 57, 52, 52, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
       46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 51, 51, 51, 51, 51, 51, 51,
       51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 35, 35, 35, 35, 35, 35, 35,
       35, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 53, 53, 53, 53, 53,
       53, 53, 53, 53, 53,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 43, 43, 43, 43,
       43, 43, 43, 43, 43, 43, 43, 36, 58, 52, 58, 58, 58, 58, 58, 44, 44,
       44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 18, 37, 37, 37, 37, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55

In [ ]:
output_df = pd.DataFrame({
    'Predicted labels before feature engineering': y_pred_test,
    'Predicted labels after feature engineering': y_pred_test_fe,
    'No. of new features': x_test_trf.shape[1]
})


for i in range(x_test_trf.shape[1]):
    output_df[f'New feature {i+1}'] = x_test_trf.iloc[:, i]
output_df
output_df.to_csv('/content/drive/MyDrive/Colab Notebooks/190294K_label_1.csv',index=False)

**Label 2**

Without Feature Engineering

In [ ]:
x_train[L2]

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0      -1.478075  -0.919153  -0.122854   0.190992   0.532721   0.083195   
1      -0.164468  -0.168904   0.707648   0.863136   0.500324   0.655473   
2      -1.104839  -0.495742   0.280910   0.694052   0.127613  -0.383403   
3      -0.003102  -1.363269   0.554493  -0.203880   0.627494   0.006706   
4      -0.245420  -0.128128  -0.890594   0.327789   0.215869   0.411213   
...          ...        ...        ...        ...        ...        ...   
28035   0.041445   1.189802  -0.142396   0.022144   2.639956  -0.065099   
28036   1.222926  -0.535411   0.059296  -0.011324   0.280107  -0.266280   
28037   1.003279  -0.017977   0.123935   0.312931   1.068010   0.212752   
28038  -0.612983  -0.009674   0.017086  -0.612319   0.888715  -0.587050   
28039   0.767063  -0.207868   0.467882  -0.431492   0.961490  -0.453202   

       feature_7  feature_8  feature_9  feature_10  ...  feature_247  \
0      -0.413296   1.618364  -0.361684    0.922091  ...     0.392840   
1       0.367621   0.459122  -0.115466   -0.415692  ...    -0.887951   
2       0.115028  -0.106487  -0.438117    0.603185  ...     0.622465   
3       0.805259   0.530926  -1.246632    0.955617  ...    -0.419594   
4      -1.192756   0.616893   0.049771   -0.185977  ...    -0.281914   
...          ...        ...        ...         ...  ...          ...   
28035  -0.975244   0.167776   1.201813    0.556369  ...     0.690244   
28036   0.760567  -1.634607  -0.124961    0.086491  ...     0.701165   
28037   0.237290  -0.049874   0.227514    0.621372  ...     0.351412   
28038   0.130273  -0.873496   0.217626   -0.735412  ...     0.483689   
28039   0.601624   0.916398  -1.017462    1.542311  ...     0.094080   

       feature_248  feature_249  feature_250  feature_251  feature_252  \
0        -0.528180    -0.083242     0.600690    -0.443301     1.484652   
1         0.093141    -0.719624    -0.092054     0.931119     0.278431   
2         0.366905     0.719441     0.564372     0.207672     0.503795   
3        -0.093203    -0.039681     0.264457     0.819096    -0.890674   
4        -0.918900     0.965921     0.754784    -0.610062     0.596708   
...            ...          ...          ...          ...          ...   
28035    -0.160700    -0.540798     1.254211     0.560265    -0.774734   
28036    -0.435428    -0.044028     0.884075    -0.136116     0.039582   
28037    -0.182745    -0.401442    -0.955139     0.843807    -1.398489   
28038     0.306146     0.653486     0.231333     0.533451    -0.433915   
28039    -0.089739    -1.348772    -0.404091     0.967211    -0.811067   

       feature_253  feature_254  feature_255  feature_256  
0        -0.585782    -1.040437     0.195293     0.225768  
1         0.047282     0.229236    -0.578322    -0.212124  
2         0.031109    -0.460085    -0.524868    -0.352231  
3         0.827678    -0.375850    -0.319669    -0.476607  
4         0.563620    -0.187139    -0.058229     0.425574  
...            ...          ...          ...          ...  
28035    -0.723551     0.918781     0.566787     0.445773  
28036    -0.155878    -0.308519     0.898501    -0.277834  
28037     0.771168     1.392149    -0.216609    -0.202054  
28038     0.081457    -0.178080    -1.037466    -0.070564  
28039     1.063342     1.254260    -0.026932    -1.241248  

[28040 rows x 256 columns]

In [ ]:
# Training the model to predict label_2
from sklearn import svm

clf = svm.SVC(kernel='linear')

clf.fit(x_train[L2], y_train[L2])

SVC(kernel='linear')

In [ ]:
from sklearn import metrics

y_pred_2 = clf.predict(x_valid[L2]) # Predicting the validation data set

In [ ]:
# accuracy of the validation data set
print(metrics.confusion_matrix(y_valid[L2], y_pred_2))
print(metrics.accuracy_score(y_valid[L2], y_pred_2))
print(metrics.precision_score(y_valid[L2], y_pred_2, average='weighted'))
print(metrics.recall_score(y_valid[L2], y_pred_2, average='weighted'))

[[34  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 60  1  5  4  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0 40  0  4  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  8  1 65  1  0  0  0  2  1  0  0  0  0  0  0  0]
 [ 0  2  2  4 99  4  0  1  0  3  0  0  0  0  0  0  0]
 [ 0  2  3  1  3 69  0  1  1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  2 41  0  0  0  0  0  0  0  0  0  0]
 [ 2  1  0  0  1  0  0 41  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  1  2  0  0 43  0  0  0  0  0  0  0  0]
 [ 1  0  0  3  2  2  0  0  1 55  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0 29  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0 18]]
0.8817934782608695
0.8839786971807817
0.8817934782608695


In [ ]:
# predicting the label_3 of the test data set
y_pred_test = clf.predict(x_test[L2])

In [ ]:
y_pred_test

array([27., 30., 30., 25., 27., 30., 25., 27., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25., 27., 23., 27., 27., 27., 27., 24., 27.,
       23., 23., 27., 23., 23., 23., 23., 25., 23., 25., 23., 23., 23.,
       23., 23., 23., 33., 33., 33., 33., 33., 33., 33., 33., 33., 33.,
       33., 33., 34., 34., 34., 34., 34., 34., 34., 34., 34., 34., 34.,
       22., 22., 22., 22., 23., 22., 26., 22., 22., 22., 30., 30., 30.,
       30., 30., 25., 30., 30., 30., 30., 30., 30., 30., 33., 30., 30.,
       30., 27., 30., 30., 26., 26., 26., 26., 26., 26., 26., 26., 26.,
       26., 26., 26., 29., 26., 26., 26., 26., 26., 24., 24., 24., 26.,
       24., 24., 24., 24., 24., 24., 24., 24., 24., 24., 24., 24., 31.,
       24., 24., 24., 24., 24., 24., 24., 24., 24., 24., 24., 31., 31.,
       31., 31., 31., 31., 31., 31., 31., 31., 26., 26., 26., 26., 26.,
       26., 26., 26., 26., 26., 26., 26., 29., 26., 26., 31., 31., 31.,
       31., 22., 34., 31., 31., 31., 31., 31., 22., 29., 29., 29

With Feature Engineering

In [ ]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsRegressor  # Import KNeighborsRegressor
from sklearn import metrics

selector = SelectKBest(f_classif, k=50)
x_train_new = selector.fit_transform(x_train[L2], y_train[L2])


In [ ]:
# Applying PCA to selected features
pca = PCA(n_components=0.95, svd_solver='full')
x_train_pca = pca.fit_transform(x_train_new)
print("Shape after PCA: ", x_train_pca.shape)


Shape after PCA:  (28040, 32)


In [ ]:
# Creating a validation set with feature transformations
x_valid_new = selector.transform(x_valid[L2])
x_valid_pca = pca.transform(x_valid_new)

x_test_new = selector.transform(x_test[L2])
x_test_pca = pca.transform(x_test_new)


In [ ]:
# Creating a KNN regressor
regressor = KNeighborsRegressor(n_neighbors=5)

# Fitting the KNN regressor
regressor.fit(x_train_pca, y_train[L2])


KNeighborsRegressor()

In [ ]:
# Make predictions on the validation set
y_pred = regressor.predict(x_valid_pca)

# KNN regressor's performance
print("Mean Absolute Error:", metrics.mean_absolute_error(y_valid[L2], y_pred))
print("Mean Squared Error:", metrics.mean_squared_error(y_valid[L2], y_pred))
print("R-squared:", metrics.r2_score(y_valid[L2], y_pred))



Mean Absolute Error: 0.3885869565217391
Mean Squared Error: 2.672717391304347
R-squared: 0.9370134013334379


In [ ]:
# Make predictions on the test set
y_pred_test_fe = regressor.predict(x_test_pca)

Predicted values before feature engineering: [26.6 27.8 28.2 30.2 27.8 26.  25.  25.  25.  25.  25.  25.  25.  25.
 25.  25.  26.2 25.  27.  27.  27.  27.  27.  27.  27.  25.2 23.  24.4
 23.6 23.  23.6 24.2 25.  23.  25.6 24.  25.2 23.  24.8 23.6 23.  23.
 32.4 33.  33.  33.  33.  33.  33.  33.  33.  33.  33.  33.  34.  26.8
 34.  32.6 34.  34.  34.  34.  34.  34.  34.  22.  22.  22.  22.  22.
 22.  22.  22.  22.  22.  30.  30.  30.  30.  30.  30.  30.  30.  29.4
 30.6 30.  30.  36.2 30.6 27.4 30.  30.  30.  30.  30.  28.  29.2 24.6
 26.  26.  26.  26.6 26.  25.2 26.  26.  26.  26.  26.  26.  26.  26.
 24.4 23.8 24.  24.  24.  24.  24.  24.  24.  24.  24.  24.  24.  24.
 24.  25.6 24.  24.  24.  24.  24.  24.  24.  23.6 24.  25.  27.4 24.
 24.  31.  31.  31.  31.  31.  31.  31.  31.  31.  31.  26.  26.  26.
 26.  26.  26.  26.  25.4 26.  26.  25.  26.  26.  26.  26.  31.  29.2
 31.  31.  31.  33.4 31.  31.  31.  29.2 31.  27.6 29.  29.  29.  29.
 29.  29.  29.  39.4 46.6 61.  61.  61. 

In [ ]:
output_df = pd.DataFrame({
    'Predicted labels before feature engineering': y_pred_test,
    'Predicted labels after feature engineering': y_pred_test_fe,
    'No. of new features': x_test_pca.shape[1]
})

for i in range(x_test_pca.shape[1]):
    output_df[f'New feature {i+1}'] = x_test_pca[:, i]
output_df
output_df.to_csv('/content/drive/MyDrive/Colab Notebooks/190294K_label_2.csv',index=False)

**Label 3**

Without Feature Engineering

In [ ]:
x_train[L3]

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0      -1.309586   0.235701   0.943739   1.110687   0.493583  -0.232368   
1      -1.144159  -0.295674   0.837377   2.514509  -0.718433   1.537233   
2      -1.292525   0.186803  -0.330437   2.726045  -0.915203   1.013608   
3       0.669594  -1.191524  -0.251777   0.560848   0.193810   0.728978   
4      -1.345805   0.084043   0.418116   2.155265  -0.227710   1.064978   
...          ...        ...        ...        ...        ...        ...   
28515   0.043336   1.192542  -0.149975   0.011312   2.636595  -0.068369   
28516   1.215430  -0.535137   0.051517  -0.021644   0.280856  -0.269055   
28517   0.997528  -0.016963   0.116092   0.297648   1.067387   0.208798   
28518  -0.605893  -0.008649   0.009349  -0.613440   0.888404  -0.589037   
28519   0.763188  -0.207126   0.459697  -0.435380   0.961052  -0.455518   

       feature_7  feature_8  feature_9  feature_10  ...  feature_247  \
0      -0.624554  -0.504571   0.132999    0.095217  ...     1.583006   
1       0.286751  -0.431414   1.105227   -0.783768  ...     1.036040   
2       1.247330  -1.564947   0.951931   -1.012765  ...     0.297848   
3       0.931314   0.170499   1.527067    0.288711  ...     0.829376   
4      -0.248008   0.090402   0.538791   -1.573073  ...     1.058010   
...          ...        ...        ...         ...  ...          ...   
28515  -0.978061   0.177880   1.175240    0.563477  ...     0.670030   
28516   0.761116  -1.611506  -0.137716    0.093801  ...     0.680854   
28517   0.236824  -0.038200   0.211088    0.628452  ...     0.334185   
28518   0.129601  -0.855883   0.201302   -0.727748  ...     0.465296   
28519   0.601866   0.921103  -1.020922    1.548995  ...     0.079121   

       feature_248  feature_249  feature_250  feature_251  feature_252  \
0         1.101137    -0.786061     0.622750    -0.503841    -0.862208   
1        -0.688550    -1.640606    -0.053767    -0.486404    -0.493145   
2         0.303437    -2.323521    -0.182392    -0.006368     0.086269   
3        -0.102070    -2.596694    -0.616500     0.544197     0.307588   
4        -0.117040    -1.419770     0.362046    -0.435119    -0.786176   
...            ...          ...          ...          ...          ...   
28515    -0.158732    -0.525769     1.257927     0.567362    -0.776576   
28516    -0.432984    -0.031154     0.887144    -0.127631     0.039676   
28517    -0.180739    -0.387017    -0.955283     0.850339    -1.401814   
28518     0.307306     0.663333     0.233262     0.540602    -0.434947   
28519    -0.087894    -1.330237    -0.403272     0.973497    -0.812996   

       feature_253  feature_254  feature_255  feature_256  
0        -1.063657    -0.033389    -0.726253     0.785181  
1        -1.293456    -0.320623     0.746471    -0.660619  
2         0.762691     0.577715    -0.946525    -0.585987  
3        -0.577020     0.401594    -1.154003     0.207497  
4         0.068403    -0.787532     1.939043     0.183946  
...            ...          ...          ...          ...  
28515    -0.718924     0.924023     0.570760     0.442692  
28516    -0.151647    -0.303670     0.903381    -0.282937  
28517     0.774752     1.397541    -0.214777    -0.206945  
28518     0.085522    -0.173189    -1.037877    -0.075089  
28519     1.066722     1.259609    -0.024581    -1.249044  

[28520 rows x 256 columns]

In [ ]:
# Training the model to predict label_1
from sklearn import svm

clf = svm.SVC(kernel='linear')

clf.fit(x_train[L3], y_train[L3])

SVC(kernel='linear')

In [ ]:
from sklearn import metrics

y_pred_3 = clf.predict(x_valid[L3]) # Predicting the validation data set

In [ ]:
# accuracy of the validation data set
print(metrics.confusion_matrix(y_valid[L3], y_pred_3))
print(metrics.accuracy_score(y_valid[L3], y_pred_3))
print(metrics.precision_score(y_valid[L3], y_pred_3, average='weighted'))
print(metrics.recall_score(y_valid[L3], y_pred_3, average='weighted'))

[[142   0]
 [  1 607]]
0.9986666666666667
0.9986759906759908
0.9986666666666667


In [ ]:
# predicting the label_3 of the test data set
y_pred_test = clf.predict(x_test[L3])

In [ ]:
y_pred_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

With Feature Engineering

In [ ]:
# With  selectKBest method
from sklearn.feature_selection import SelectKBest, f_classif

selector =  SelectKBest(f_classif, k=10) #  with only using 10 features
x_new_train = selector.fit_transform(x_train[L1], y_train[L1])
x_new_valid = selector.transform(x_valid[L1])
x_new_test = selector.transform(x_test[L1])
print('shape training', x_new_train.shape)
print('shape validation', x_new_valid.shape)
print('shape test', x_new_test.shape)

shape training (28520, 10)
shape validation (750, 10)
shape test (750, 10)


In [ ]:
clf = svm.SVC(kernel='linear')

clf.fit(x_new_train, y_train[L3])

SVC(kernel='linear')

In [ ]:
y_pred_3 = clf.predict(selector.transform(x_valid[L3]))
print(metrics.confusion_matrix(y_valid[L3], y_pred_3))
print(metrics.accuracy_score(y_valid[L3], y_pred_3))
print(metrics.precision_score(y_valid[L3], y_pred_3, average='weighted'))
print(metrics.recall_score(y_valid[L3], y_pred_3, average='weighted'))

[[138   4]
 [ 12 596]]
0.9786666666666667
0.9794488888888888
0.9786666666666667


In [ ]:
# adding PCA to the selectKBest results
from sklearn.decomposition import PCA

pca = PCA(n_components=0.95, svd_solver='full')
pca.fit(x_new_train)
x_train_trf = pd.DataFrame(pca.transform(x_new_train)) # transforming data to fit into pca
x_valid_trf = pd.DataFrame(pca.transform(x_new_valid))
x_test_trf = pd.DataFrame(pca.transform(x_new_test))
print('Shape after PCA x_train : ', x_train_trf.shape)
print('Shape after PCA x_valid : ', x_valid_trf.shape)
print('Shape after PCA x_test : ', x_valid_trf.shape)

Shape after PCA x_train :  (28520, 8)
Shape after PCA x_valid :  (750, 8)
Shape after PCA x_test :  (750, 8)


In [ ]:
clf = svm.SVC(kernel='linear')

clf.fit(x_train_trf, y_train[L3])

y_pred = clf.predict(x_valid_trf)
print(metrics.confusion_matrix(y_valid[L3], y_pred))
print(metrics.accuracy_score(y_valid[L3], y_pred))
print(metrics.precision_score(y_valid[L3], y_pred, average='weighted'))
print(metrics.recall_score(y_valid[L3], y_pred, average='weighted'))

[[139   3]
 [ 12 596]]
0.98
0.9808935422171611
0.98


In [ ]:
# predicting the test data
y_pred_test_fe = clf.predict(x_test_trf)
y_pred_test_fe

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
output_df = pd.DataFrame({
    'Predicted labels before feature engineering': y_pred_test,
    'Predicted labels after feature engineering': y_pred_test_fe,
    'No. of new features': x_test_trf.shape[1]
})


for i in range(x_test_trf.shape[1]):
    output_df[f'New feature {i+1}'] = x_test_trf.iloc[:, i]
output_df
output_df.to_csv('/content/drive/MyDrive/Colab Notebooks/190294K_label_3.csv',index=False)

**For Label 4**

Without Feature Engineering

In [ ]:
x_train[L4]

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0      -1.309586   0.235701   0.943739   1.110687   0.493583  -0.232368   
1      -1.144159  -0.295674   0.837377   2.514509  -0.718433   1.537233   
2      -1.292525   0.186803  -0.330437   2.726045  -0.915203   1.013608   
3       0.669594  -1.191524  -0.251777   0.560848   0.193810   0.728978   
4      -1.345805   0.084043   0.418116   2.155265  -0.227710   1.064978   
...          ...        ...        ...        ...        ...        ...   
28515   0.043336   1.192542  -0.149975   0.011312   2.636595  -0.068369   
28516   1.215430  -0.535137   0.051517  -0.021644   0.280856  -0.269055   
28517   0.997528  -0.016963   0.116092   0.297648   1.067387   0.208798   
28518  -0.605893  -0.008649   0.009349  -0.613440   0.888404  -0.589037   
28519   0.763188  -0.207126   0.459697  -0.435380   0.961052  -0.455518   

       feature_7  feature_8  feature_9  feature_10  ...  feature_247  \
0      -0.624554  -0.504571   0.132999    0.095217  ...     1.583006   
1       0.286751  -0.431414   1.105227   -0.783768  ...     1.036040   
2       1.247330  -1.564947   0.951931   -1.012765  ...     0.297848   
3       0.931314   0.170499   1.527067    0.288711  ...     0.829376   
4      -0.248008   0.090402   0.538791   -1.573073  ...     1.058010   
...          ...        ...        ...         ...  ...          ...   
28515  -0.978061   0.177880   1.175240    0.563477  ...     0.670030   
28516   0.761116  -1.611506  -0.137716    0.093801  ...     0.680854   
28517   0.236824  -0.038200   0.211088    0.628452  ...     0.334185   
28518   0.129601  -0.855883   0.201302   -0.727748  ...     0.465296   
28519   0.601866   0.921103  -1.020922    1.548995  ...     0.079121   

       feature_248  feature_249  feature_250  feature_251  feature_252  \
0         1.101137    -0.786061     0.622750    -0.503841    -0.862208   
1        -0.688550    -1.640606    -0.053767    -0.486404    -0.493145   
2         0.303437    -2.323521    -0.182392    -0.006368     0.086269   
3        -0.102070    -2.596694    -0.616500     0.544197     0.307588   
4        -0.117040    -1.419770     0.362046    -0.435119    -0.786176   
...            ...          ...          ...          ...          ...   
28515    -0.158732    -0.525769     1.257927     0.567362    -0.776576   
28516    -0.432984    -0.031154     0.887144    -0.127631     0.039676   
28517    -0.180739    -0.387017    -0.955283     0.850339    -1.401814   
28518     0.307306     0.663333     0.233262     0.540602    -0.434947   
28519    -0.087894    -1.330237    -0.403272     0.973497    -0.812996   

       feature_253  feature_254  feature_255  feature_256  
0        -1.063657    -0.033389    -0.726253     0.785181  
1        -1.293456    -0.320623     0.746471    -0.660619  
2         0.762691     0.577715    -0.946525    -0.585987  
3        -0.577020     0.401594    -1.154003     0.207497  
4         0.068403    -0.787532     1.939043     0.183946  
...            ...          ...          ...          ...  
28515    -0.718924     0.924023     0.570760     0.442692  
28516    -0.151647    -0.303670     0.903381    -0.282937  
28517     0.774752     1.397541    -0.214777    -0.206945  
28518     0.085522    -0.173189    -1.037877    -0.075089  
28519     1.066722     1.259609    -0.024581    -1.249044  

[28520 rows x 256 columns]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train[L4], y_train[L4])

KNeighborsClassifier(n_neighbors=3)

In [ ]:
from sklearn import metrics

y_pred = knn.predict(x_valid[L4]) # Predicting the validation data set

In [ ]:
# accuracy of the validation data set
print(metrics.confusion_matrix(y_valid[L4], y_pred))
print(metrics.accuracy_score(y_valid[L4], y_pred))
print(metrics.precision_score(y_valid[L4], y_pred, average='weighted'))
print(metrics.recall_score(y_valid[L4], y_pred, average='weighted'))

[[ 21   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  11   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  27   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   8   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  15   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  10   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 532   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1  31   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0  18   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  17   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  10   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  11   0   0]
 [  0   0   0   0   0   0   1   1   0   0   0   0  24   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  10]]
0.9933333333333333
0.9933731343283582
0.9933333333333333


In [ ]:
# predicting the label_4 of the test data set
y_pred_test = knn.predict(x_test[L4])

In [ ]:
y_pred_test

array([ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6, 13, 13, 13, 13, 13, 13, 13,  2,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  6,  4,  4,  4,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  2,  2,  2,  2,  2,  2,  2,
        2,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7, 12,  7,  7,  7,  7,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6

With Feature Engineering

In [ ]:
# With  selectKBest method
from sklearn.feature_selection import SelectKBest, f_classif

selector =  SelectKBest(f_classif, k=40) #  with only using 40 features
x_new_train = selector.fit_transform(x_train[L4], y_train[L4])
x_new_valid = selector.transform(x_valid[L4])
x_new_test = selector.transform(x_test[L4])
print('shape training', x_new_train.shape)
print('shape validation', x_new_valid.shape)
print('shape test', x_new_test.shape)

shape training (28520, 40)
shape validation (750, 40)
shape test (750, 40)


In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_new_train, y_train[L4])

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = knn.predict(selector.transform(x_valid[L4]))
print(metrics.confusion_matrix(y_valid[L4], y_pred))
print(metrics.accuracy_score(y_valid[L4], y_pred))
print(metrics.precision_score(y_valid[L4], y_pred, average='weighted'))
print(metrics.recall_score(y_valid[L4], y_pred, average='weighted'))

[[ 19   0   0   0   0   0   2   0   0   0   0   0   0   0]
 [  0  10   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0  26   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   7   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0  15   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  10   1   0   0   0   0   0   0   0]
 [  2   0   1   0   0   0 529   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1  31   0   0   0   0   0   0]
 [  0   0   0   0   0   0   2   0  17   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  17   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  10   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  11   0   0]
 [  0   0   0   0   0   0   4   0   0   0   0   0  22   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  10]]
0.9786666666666667
0.9789864698646987
0.9786666666666667


In [ ]:
# adding PCA to the selectKBest results
from sklearn.decomposition import PCA

pca = PCA(n_components=0.95, svd_solver='full')
pca.fit(x_new_train)
x_train_trf = pd.DataFrame(pca.transform(x_new_train)) # transforming data to fit into pca
x_valid_trf = pd.DataFrame(pca.transform(x_new_valid))
x_test_trf = pd.DataFrame(pca.transform(x_new_test))
print('Shape after PCA x_train : ', x_train_trf.shape)
print('Shape after PCA x_valid : ', x_valid_trf.shape)
print('Shape after PCA x_test : ', x_valid_trf.shape)

Shape after PCA x_train :  (28520, 28)
Shape after PCA x_valid :  (750, 28)
Shape after PCA x_test :  (750, 28)


In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train_trf, y_train[L4])

y_pred = knn.predict(x_valid_trf)
print(metrics.confusion_matrix(y_valid[L4], y_pred))
print(metrics.accuracy_score(y_valid[L4], y_pred))
print(metrics.precision_score(y_valid[L4], y_pred, average='weighted'))
print(metrics.recall_score(y_valid[L4], y_pred, average='weighted'))

[[ 18   0   1   0   0   0   2   0   0   0   0   0   0   0]
 [  0  11   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  26   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   7   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0  15   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  10   1   0   0   0   0   0   0   0]
 [  2   0   1   0   0   0 527   0   0   1   0   0   1   0]
 [  0   0   0   0   0   0   2  30   0   0   0   0   0   0]
 [  0   0   0   0   0   0   4   1  14   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  17   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  10   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  11   0   0]
 [  0   0   0   0   0   0   3   0   0   0   0   0  23   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  10]]
0.972
0.9721923930165417
0.972


In [ ]:
# predicting the test data
y_pred_test_fe = knn.predict(x_test_trf)
y_pred_test_fe

array([ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6, 13, 13, 13, 13, 13, 13, 13,  2,  0,  6,  4,  4,  4,  4,  4,  4,
        4,  4,  1,  4,  4,  4,  4,  4,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  2,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  2,  2,  2,  2,  2,  6,  2,
        2,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  0,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  0,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  6,  7,  7,  6,  7,  7,  7,  7,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6

In [ ]:
output_df = pd.DataFrame({
    'Predicted labels before feature engineering': y_pred_test,
    'Predicted labels after feature engineering': y_pred_test_fe,
    'No. of new features': x_test_trf.shape[1]
})


for i in range(x_test_trf.shape[1]):
    output_df[f'New feature {i+1}'] = x_test_trf.iloc[:, i]
output_df
output_df.to_csv('/content/drive/MyDrive/Colab Notebooks/190294K_label_4.csv',index=False)